# Generated by Django 4.2.11 on 2024-05-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=254)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_born_date', models.DateField()),
                ('client_cpf', models.CharField(max_length=11)),
                ('client_has_license_plate', models.BooleanField()),
                ('client_conductor_relation', models.IntegerField(choices=[(0, 'O próprio'), (1, 'O próprio com CRV em transferência'), (2, 'Cônjuge/Companheiro(a)'), (3, 'Pai/Mãe'), (4, 'Filho(a)/Enteado(a)'), (5, 'Condutor indeterminado'), (6, 'Outros')])),
                ('conductor_name', models.CharField(max_length=254)),
                ('conductor_cpf', models.CharField(max_length=11)),
                ('conductor_gender', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Outros')])),
                ('conductor_born_date', models.DateField()),
                ('conductor_marital_status', models.IntegerField(choices=[(0, 'Casado(a)'), (1, 'Reside com companheiro(a) / Namorado(a)'), (2, 'Solteiro(a)'), (3, 'Viúvo(a)'), (4, 'Divorciado(a)')])),
                ('conductor_extended_coverage', models.IntegerField(choices=[(0, 'Sim, porém são maiores que 24 anos e menores que 26 anos.'), (1, 'Não tem condutores menores de 26 anos.'), (2, 'Sim, e são menores de 24 anos.'), (3, 'Sim, porém não dirige o veículo')])),
                ('storage_cep', models.CharField(max_length=20)),
                ('use_type', models.IntegerField(choices=[(0, 'Particular (locomoção diária)'), (1, 'Particular (somente para lazer)'), (2, 'Utilizado para visitas ou representação comercial'), (3, 'Utilizado para transporte de passageiros'), (4, 'Utilizado para entregas')])),
                ('is_rebranded_chassis', models.BooleanField()),
                ('is_alienado', models.BooleanField()),
                ('is_customized', models.BooleanField()),
                ('is_armored', models.BooleanField()),
                ('have_gas_kit', models.BooleanField()),
                ('live_in', models.IntegerField(choices=[(0, 'Casa/Sobrado'), (1, 'Apartamento'), (2, 'Condomínio de Casas'), (3, 'Outros')])),
                ('storage_type', models.IntegerField(choices=[(0, 'Sim, com portão manual'), (1, 'Sim, com portão automático'), (2, 'Sim, em estacionamento privado ou pago'), (3, 'Não')])),
                ('is_to_work', models.IntegerField(choices=[(0, 'Sim'), (1, 'Não'), (2, 'Não trabalha')])),
                ('is_to_college', models.IntegerField(choices=[(0, 'Sim, Ensino Médio'), (1, 'Sim, Ensino Superior'), (2, 'Sim, Pós-Graduação'), (3, 'Sim, Outros'), (4, 'Estuda mas não utiliza o veículo'), (5, 'Não estuda')])),
                ('trust_check', models.BooleanField()),
            ],
        ),
    ]
