# Generated by Django 4.2.11 on 2024-05-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='answered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
