# Generated by Django 4.2.11 on 2024-05-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_answered_client_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_phone_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
