# Generated by Django 4.2.11 on 2024-05-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='conductor_extended_coverage',
            field=models.IntegerField(choices=[(0, 'Sim, porém são maiores que 24 anos e menores que 26 anos.'), (1, 'Não tem condutores menores de 26 anos.'), (2, 'Sim, e são menores de 24 anos.'), (3, 'Sim, porém não dirige o veículo'), (4, 'Não')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='trust_check',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
