# Generated by Django 4.2.11 on 2024-05-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
